### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [smnnlt/spiro#5]
Hi

We are preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are related to ggborderline and not directly caused by your own code. The ggborderline developers have been notified and this is as much to inform you about the issue, should ggborderline not get fixed in time

You can install the release candidate of ggplot2 using devtools::install_github('tidyverse/ggplot2@v3.4.0-rc') to test this out.

We plan to submit ggplot2 by the end of October.

Kind regards
Thomas

**Comment by smnnlt** [comment]
This should be resolved with the recent ggborderline update to version 0.2.0.
